# Generated by Django 5.0.2 on 2024-03-02 15:47

import celebrities.services
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityOccupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=celebrities.services.get_celebrity_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('bio', models.TextField(blank=True, max_length=5000, null=True)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('spouses', models.CharField(blank=True, max_length=300, null=True)),
                ('children', models.CharField(blank=True, max_length=300, null=True)),
                ('parents', models.CharField(blank=True, max_length=300, null=True)),
                ('occupations', models.ManyToManyField(blank=True, related_name='celebrities', to='celebrities.celebrityoccupations')),
                ('birth_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebrities', to='celebrities.countries')),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=celebrities.services.get_celebrity_photos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='celebrities.celebrity')),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=celebrities.services.get_celebrity_videos, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3'])])),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='celebrities.celebrity')),
            ],
        ),
    ]
