# Generated by Django 5.0.2 on 2024-03-02 15:47

import django.core.validators
import django.db.models.deletion
import movies.services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=movies.services.get_movie_poster, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('released', models.BooleanField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('trailer', models.FileField(blank=True, null=True, upload_to=movies.services.get_movie_trailer, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3'])])),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('box_office', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='actormovies', to='celebrities.celebrity')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='celebrities.countries')),
                ('directors', models.ManyToManyField(blank=True, related_name='directormovies', to='celebrities.celebrity')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genres')),
                ('languages', models.ManyToManyField(blank=True, related_name='movies', to='movies.languages')),
                ('main_cast', models.ManyToManyField(blank=True, related_name='mainactormovies', to='celebrities.celebrity')),
                ('producers', models.ManyToManyField(blank=True, related_name='producermovies', to='celebrities.celebrity')),
                ('writers', models.ManyToManyField(blank=True, related_name='writermovies', to='celebrities.celebrity')),
            ],
        ),
        migrations.CreateModel(
            name='MovieReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movies')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movies')),
            ],
        ),
        migrations.CreateModel(
            name='MoviePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=movies.services.get_movie_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='movies.movies')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('celebrity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebcharacters', to='celebrities.celebrity')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviecharacters', to='movies.movies')),
            ],
        ),
        migrations.CreateModel(
            name='MovieVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=movies.services.get_movie_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3'])])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movies.movies')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planned_movies', to='movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
