# Generated by Django 5.0.2 on 2024-03-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
        ('movies', '0002_alter_plannedmovies_movie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecharacters',
            name='celebrity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviecharacters', to='celebrities.celebrity'),
        ),
        migrations.AlterField(
            model_name='movieratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moviereviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviereviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
