# Generated by Django 5.0.2 on 2024-03-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviereviews_likes_moviereviewlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereviewlikes',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='moviereviewlikes',
            name='liked',
        ),
    ]
