# Generated by Django 5.0.2 on 2024-03-03 11:53

import django.core.validators
import django.db.models.deletion
import tv_shows.services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrities', '0001_initial'),
        ('movies', '0003_alter_moviecharacters_celebrity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('poster', models.ImageField(upload_to=tv_shows.services.get_tv_show_poster, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('season', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('release_start_date', models.DateField(blank=True, null=True)),
                ('release_end_date', models.DateField(blank=True, null=True)),
                ('released', models.BooleanField()),
                ('ongoing', models.BooleanField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('trailer', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mp3'])])),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('box_office', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='actorshows', to='celebrities.celebrity')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='celebrities.countries')),
                ('directors', models.ManyToManyField(blank=True, related_name='directorshows', to='celebrities.celebrity')),
                ('genres', models.ManyToManyField(blank=True, related_name='tv_shows', to='movies.genres')),
                ('languages', models.ManyToManyField(blank=True, related_name='tv_shows', to='movies.languages')),
                ('main_cast', models.ManyToManyField(blank=True, related_name='mainactorshows', to='celebrities.celebrity')),
                ('producers', models.ManyToManyField(blank=True, related_name='producershows', to='celebrities.celebrity')),
                ('writers', models.ManyToManyField(blank=True, related_name='writershows', to='celebrities.celebrity')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTVShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_tvshows', to=settings.AUTH_USER_MODEL)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_tvshows', to='tv_shows.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('celebrity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tvshowcharacters', to='celebrities.celebrity')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvshowcharacters', to='tv_shows.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=tv_shows.services.get_tv_show_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tv_shows.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TVShowRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvshowratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvshowreviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=tv_shows.services.get_tv_show_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3'])])),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tv_shows.tvshow')),
            ],
        ),
    ]
