# Generated by Django 5.0.2 on 2024-03-03 19:07

import django.core.validators
import django.db.models.deletion
import tv_shows.services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='episodes',
            new_name='episodes_count',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='trailer',
            field=models.FileField(upload_to=tv_shows.services.get_tv_show_trailer, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mp3'])]),
        ),
        migrations.CreateModel(
            name='TVEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=8000)),
                ('poster', models.ImageField(upload_to=tv_shows.services.get_tv_episode_poster, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('trailer', models.FileField(upload_to=tv_shows.services.get_tv_episode_trailer, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3'])])),
                ('released', models.BooleanField(default=True)),
                ('release_date', models.DateField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tv_shows.tvshow')),
            ],
        ),
        migrations.CreateModel(
            name='TVEpisodeReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvepisodereviews', to=settings.AUTH_USER_MODEL)),
                ('tv_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tv_shows.tvepisodes')),
            ],
        ),
        migrations.CreateModel(
            name='TVEpisodeRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvepisoderatings', to=settings.AUTH_USER_MODEL)),
                ('tv_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tv_shows.tvepisodes')),
            ],
        ),
        migrations.CreateModel(
            name='TVEpisodePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=tv_shows.services.get_tv_episode_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('tv_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tv_shows.tvepisodes')),
            ],
        ),
        migrations.CreateModel(
            name='TVEpisodeVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=tv_shows.services.get_tv_episode_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3'])])),
                ('tv_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tv_shows.tvepisodes')),
            ],
        ),
    ]
