# Generated by Django 5.0.2 on 2024-03-03 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0002_rename_episodes_tvshow_episodes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisodes',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
