# Generated by Django 5.0.2 on 2024-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0003_tvepisodes_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='runtime',
        ),
        migrations.AddField(
            model_name='tvepisodes',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
