# Generated by Django 5.0.2 on 2024-03-04 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0004_remove_tvshow_runtime_tvepisodes_runtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisodereviews',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tvshowreviews',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TVEpisodeReviewLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='tv_shows.tvepisodereviews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_episode_review_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowReviewLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='tv_shows.tvshowreviews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_show_review_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
